select * from BugNet_HostSettings  
select * from BugNet_Languages  
select * from BugNet_ProjectCustomFieldTypes  
select * from BugNet_RequiredFieldList 
select * from bugissue 
select * from bugstatusenvir
select * from categories  
select * from orgs  
select * from priorities 
select * from project_user_xref 
select * from queries 
select * from reports  
select * from sessions  
select * from statuses  
select * from user_defined_attribute  
select * from bug_posts 
select * from bug_subscriptions 
select * from bug_user 
select * from bugs 
select * from custom_col_metadata
select * from projects p 
select * from queued_notifications
select * from users